apiVersion: v2
name: victoriametricstest
description: Helm chart for deploying VictoriaMetrics cluster, Grafana, and the Spam2000 app for Kubernetes monitoring.
version: 0.1.0
appVersion: "1.1394.355"
dependencies:
  - name: victoria-metrics-cluster
    version: 0.11.1
    repository: https://victoriametrics.github.io/helm-charts/
  - name: grafana
    version: 8.5.1
    repository: https://grafana.github.io/helm-charts/
