{
 "title": "Spam2000 App Metrics Dashboard",
 "templating": {
  "list": [
   {
    "name": "product",
    "label": "Product",
    "query": "label_values(app_total_requests, product)"
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": "label_values(app_total_requests, platform)"
   },
   {
    "name": "email",
    "label": "Email",
    "query": "label_values(app_total_requests, email)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(app_total_requests, name)"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "label_values(app_total_requests, country)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests Processed",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(app_total_requests{product=~\".*$product\", platform=~\".*$platform\", email=~\".*$email\", name=~\".*$name\", country=~\".*$country\"})[5m]"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(app_success_requests{product=~\".*$product\", platform=~\".*$platform\", email=~\".*$email\", name=~\".*$name\", country=~\".*$country\"})[5m]"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(app_error_rate{product=~\".*$product\", platform=~\".*$platform\", email=~\".*$email\", name=~\".*$name\", country=~\".*$country\"})[5m]"
    }
   ]
  }
 ]
}