apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{ include "app.labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "app.selectorLabels" . }}
  template:
    metadata:
      labels:
        {{ include "app.labels" . }}
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe: {{ toYaml .Values.livenessProbe | indent 8 }}
        readinessProbe: {{ toYaml .Values.readinessProbe | indent 8 }}
        resources:
          {{ toYaml .Values.resources | indent 8 }}
