apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.fullname" . }}-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]  
  - apiGroups: ["extensions", "apps"]
    resources:
      - deployments
    verbs: ["get", "list", "watch"]  
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "list", "watch"]  
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/metrics/probes", "/metrics/resource"]
    verbs: ["get"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list", "watch"]
