apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "myApp.fullname" . }}-scrape-config"
  labels:
    myApp: vm-monitoring-testing
data:
  scrape.yaml: |-
    {{ toYaml .Values.server.scrape.config | nindent 4 }}