apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "myApp.fullname" . }}"
  labels:
    myApp: "{{ .Values.myApp.name }}"
spec:
  replicas: {{ .Values.myApp.replicaCount }}
  selector:
    matchLabels:
      myApp: "{{ .Values.myApp.name }}"
  template:
    metadata:
      labels:
        myApp: "{{ .Values.myApp.name }}"
    spec:
      serviceAccountName: "{{ include "myApp.serviceAccountName" . }}"
      containers:
        - name: "{{ .Values.myApp.name }}"
          image: "{{ .Values.myApp.image.repository }}:{{ .Values.myApp.image.tag }}"
          imagePullPolicy: {{ .Values.myApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.myApp.service.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.myApp.livenessProbe.httpGet.path }}
              port: {{ .Values.myApp.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.myApp.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.myApp.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.myApp.readinessProbe.httpGet.path }}
              port: {{ .Values.myApp.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.myApp.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.myApp.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.myApp.resources | nindent 12 }}
