apiVersion: v1
kind: Service
metadata:
  name: "{{ include "myApp.fullname" . }}"
  labels:
    {{- include "myApp.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.myApp.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  selector:
    {{- include "myApp.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.myApp.service.port }}
      targetPort: http
  type: {{ .Values.myApp.service.type }}
